"""
writer-agent.py / agent.py

Writer Agent for the Tech Book project.

Architecture:
- Uses the persisted plan.json created by the Planner Agent.
- Creates one SequentialAgent per chapter:
    - Inside each chapter agent, subsections are written in sequence.
- All chapter agents run in parallel via a ParallelAgent.
- Each subsection writer is an LlmAgent that:
    - Generates markdown for that subsection.
    - Calls the persist_subsection tool to save it to disk.

Assumptions:
- Planner Agent already ran and persisted a plan.json into:
    tech-book-agent/<book_slug>/plan.json
- For now we auto-pick the *latest* plan.json if multiple books exist.
  (You can tighten this later to use an env var BOOK_TITLE or a selector agent.)
"""

import json
import os
import re
from pathlib import Path
from typing import Dict, Any
from google.adk.models.lite_llm import LiteLlm
from google.adk.models.google_llm import Gemini

from google.adk.agents import LlmAgent, ParallelAgent, SequentialAgent

# Global retry configuration for all LLM calls in this agent
from google.genai import types

RETRY_CONFIG = types.HttpRetryOptions(
    attempts=10,           # Maximum retry attempts
    exp_base=7,           # Exponential backoff base
    initial_delay=2,      # Start with 1s delay
    http_status_codes=[   # Retry on these HTTP status codes
        429,  # Too Many Requests / rate limited / resource exhausted
        500,  # Internal server error
        503,  # Service unavailable
        504,  # Gateway timeout
    ],
)


# ---------------------------------------
# Global config & helpers
# ---------------------------------------

GEMINI_MODEL = Gemini(
                model="gemini-2.5-flash-lite",
                retry_options=RETRY_CONFIG
                )  # same as other agents
#llm =  LiteLlm(model="ollama_chat/deepseek-v3.1:671b-cloud")
PROJECT_ROOT = Path(__file__).resolve().parents[2]


def _slugify(name: str) -> str:
    name = (name or "").strip().lower()
    name = re.sub(r"[^a-z0-9]+", "-", name)
    return name.strip("-") or "untitled-book"


def _find_latest_plan() -> Dict[str, Any]:
    """
    Discover the most recently modified plan.json under tech-book-agent/*/plan.json.

    This is a *simple and pragmatic* persistence strategy:
    - Each book gets a folder: <book_slug>/
    - Planner Agent writes <book_slug>/plan.json
    - Writer Agent picks the latest modified plan.json as the active book.

    You can later replace this with:
    - an explicit BOOK_TITLE env var
    - or a supervisor agent that passes book info via tools/state.
    """
    candidate_paths = list(PROJECT_ROOT.glob("*/plan.json"))
    if not candidate_paths:
        raise FileNotFoundError(
            f"No plan.json found under {PROJECT_ROOT}. "
            "Run the planner_agent first."
        )

    # Pick the most recently modified plan.json
    latest_path = max(candidate_paths, key=lambda p: p.stat().st_mtime)

    with latest_path.open("r", encoding="utf-8") as f:
        plan = json.load(f)

    book_dir = latest_path.parent
    plan.setdefault("storage", {})
    plan["storage"].setdefault("book_dir", str(book_dir))
    plan["storage"].setdefault("plan_path", str(latest_path))
    return plan


# Load plan at import-time so we can dynamically build workflow agents
PLAN: Dict[str, Any] = _find_latest_plan()
BOOK_TITLE: str = PLAN.get("title", "Untitled Book")
BOOK_SUBTITLE: str = PLAN.get("subtitle", "")
BOOK_SLUG: str = _slugify(BOOK_TITLE)
BOOK_DIR: Path = Path(PLAN["storage"]["book_dir"])

# ---------------------------------------
# Tool: persist_subsection
# ---------------------------------------


def persist_subsection(
    book_slug: str,
    chapter_index: int,
    subsection_index: int,
    subsection_title: str,
    markdown: str,
) -> Dict[str, Any]:
    """
    Persist a single subsection's markdown content to disk.

    File layout:
      tech-book-agent/<book_slug>/chapters/chXX/subYY-<slug>.md

    Args:
        book_slug: Slugified book title (for folder).
        chapter_index: 1-based chapter index.
        subsection_index: 1-based subsection index.
        subsection_title: Title of the subsection (for filename).
        markdown: Markdown content generated by the LLM.

    Returns:
        A small metadata dict with the relative file path.
    """
    # Sanitize & resolve target folder
    slug = _slugify(book_slug)
    chapter_folder = BOOK_DIR / "chapters" / f"ch{chapter_index:02d}"
    chapter_folder.mkdir(parents=True, exist_ok=True)

    sub_slug = _slugify(subsection_title)
    filename = f"sub{subsection_index:02d}-{sub_slug}.md"
    file_path = chapter_folder / filename

    with file_path.open("w", encoding="utf-8") as f:
        f.write(markdown)

    return {
        "book_slug": slug,
        "chapter_index": chapter_index,
        "subsection_index": subsection_index,
        "path": str(file_path),
    }

# ---------------------------------------
# Dynamic construction of chapter & subsection agents
# ---------------------------------------


def build_subsection_agent(
    chapter_index: int,
    chapter_title: str,
    subsection_index: int,
    subsection: Dict[str, Any],
) -> LlmAgent:
    """
    Build an LlmAgent responsible for *one* subsection.

    It:
    - Generates markdown (~word_target words) for this subsection.
    - Calls persist_subsection() exactly once with the markdown & metadata.
    """
    sub_title = subsection.get("title", f"Subsection {subsection_index}")
    brief = subsection.get("brief", "")
    generator_prompt = subsection.get("generator_prompt", "")
    word_target = subsection.get("word_target", 600)
    keywords = subsection.get("keywords", [])

    keywords_str = ", ".join(str(k) for k in keywords)

    instruction = f"""
            You are a professional technical book author.

            You are writing a *single subsection* of a technical book.

            Book title: "{BOOK_TITLE}"
            Book subtitle: "{BOOK_SUBTITLE}"
            Chapter {chapter_index}: "{chapter_title}"
            Subsection {subsection_index}: "{sub_title}"

            Subsection brief:
            {brief}

            Generator prompt:
            {generator_prompt}

            Target length: around {word_target} words.
            Target audience: intermediate software engineers.

            Writing rules:
            - Write in **markdown**, very clear and well structured.
            - Use headings, bullet lists, and short paragraphs.
            - Highlight *key technical terms* and *important concepts* in **bold**.
            - If you include code, wrap it in fenced code blocks ```language ... ```.
            - If a table is appropriate, format it as a markdown table.
            - Do NOT reference that you are an AI. Write like a normal human author.
            - Ensure the subsection stands alone but flows logically within the chapter.

            Persistence:
            - After writing the markdown, call the `persist_subsection` tool EXACTLY ONCE.
            - Pass:
                - book_slug = "{BOOK_SLUG}"
                - chapter_index = {chapter_index}
                - subsection_index = {subsection_index}
                - subsection_title = "{sub_title}"
                - markdown = the FULL markdown you just wrote.
            - Do NOT call any other tools.
            - Do NOT print the markdown separately outside the tool call.
            """

    return LlmAgent(
        name=f"chapter_{chapter_index}_sub_{subsection_index}_writer",
        model=GEMINI_MODEL,
        instruction=instruction,
        description=(
            f"Writes subsection {subsection_index} ('{sub_title}') for "
            f"chapter {chapter_index} ('{chapter_title}') and persists it."
        ),
        tools=[persist_subsection],
        # We don't need output_key because the actual "output" is the file.
    )


def build_chapter_agent(chapter_index: int, chapter: Dict[str, Any]) -> SequentialAgent:
    """
    Build a SequentialAgent for one chapter.

    It runs all subsection writer agents in order:
      subsection_1_writer -> subsection_2_writer -> ...
    """
    chapter_title = chapter.get("chapter_title", f"Chapter {chapter_index}")
    subsections = chapter.get("subsections", [])

    subsection_agents = []
    for i, subsection in enumerate(subsections, start=1):
        subsection_agents.append(
            build_subsection_agent(
                chapter_index=chapter_index,
                chapter_title=chapter_title,
                subsection_index=i,
                subsection=subsection,
            )
        )

    # Edge case: chapter with no subsections
    if not subsection_agents:
        # A tiny agent that does nothing but acknowledge
        empty_instruction = f"""
        You are a logging agent.

        The plan indicates that Chapter {chapter_index} ('{chapter_title}')
        has no subsections defined. Simply respond with a short confirmation.
        """
        empty_agent = LlmAgent(
            name=f"chapter_{chapter_index}_empty",
            model=GEMINI_MODEL,
            instruction=empty_instruction,
            description=(
                f"Handles empty chapter {chapter_index} ('{chapter_title}') with no subsections."
            ),
        )
        subsection_agents.append(empty_agent)

    return SequentialAgent(
        name=f"chapter_{chapter_index}_writer_seq",
        sub_agents=subsection_agents,
        description=(
            f"Sequentially writes all subsections for chapter {chapter_index} "
            f"('{chapter_title}')."
        ),
    )


# ---------------------------------------
# Build batched Parallel chapter writers & Root Agent
# ---------------------------------------

chapter_agents = []
for idx, chapter in enumerate(PLAN.get("chapters", []), start=1):
    chapter_agents.append(build_chapter_agent(idx, chapter))

if not chapter_agents:
    # Fallback if the plan has no chapters
    fallback_instruction = f"""
    Planner produced no chapters for the book "{BOOK_TITLE}".

    Explain this issue to the user and suggest re-running the planner_agent.
    """
    root_agent = LlmAgent(
        name="no_chapters_fallback",
        model=GEMINI_MODEL,
        instruction=fallback_instruction,
        description="Explains that there are no chapters in the current plan.",
    )
else:
    # Read desired parallelism from env, default 2 chapters at a time
    try:
        max_parallel = int(os.getenv("WRITER_MAX_PARALLEL_CHAPTERS", "2"))
        if max_parallel < 1:
            max_parallel = 1
    except ValueError:
        max_parallel = 2

    # Create batches of chapter agents
    batches = [
        chapter_agents[i : i + max_parallel]
        for i in range(0, len(chapter_agents), max_parallel)
    ]

    batch_agents = []
    for batch_idx, batch in enumerate(batches, start=1):
        if len(batch) == 1:
            # Only one chapter in this batch – no need for ParallelAgent
            batch_agents.append(batch[0])
        else:
            batch_agents.append(
                ParallelAgent(
                    name=f"chapter_batch_{batch_idx}_parallel_writer",
                    sub_agents=batch,
                    description=(
                        f"Parallel writer for chapter batch {batch_idx}, "
                        f"handling {len(batch)} chapters."
                    ),
                )
            )

    # Now run the batches sequentially: batch1 -> batch2 -> ...
    root_agent = SequentialAgent(
        name="book_writer_pipeline",
        sub_agents=batch_agents,
        description=(
            f"Book writer pipeline for '{BOOK_TITLE}'. "
            "Chapters are processed in small batches. Each batch runs a few "
            "chapters in parallel (to improve throughput) while avoiding "
            "resource exhaustion on the LLM backend."
        ),
    )
